server:
  port: ${CARRITO_PORT:8083}
spring:
  application:
    name: msvc-carrito
  datasource:
    url: ${CARRITO_DB_URL:jdbc:postgresql://localhost:5435/carrito_db}
    username: ${CARRITO_DB_USER:postgres}
    password: ${CARRITO_DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
