spring.application.name=ms-perfil

server.port=${SERVER_PORT:8081}

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/pedidos360_perfil}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:validate}
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect