server:
  port: ${CATALOGO_PORT:8084}
spring:
  application:
    name: msvc-catalogo
  datasource:
    url: ${CATALOGO_DB_URL:jdbc:postgresql://localhost:5436/catalogo_db}
    username: ${CATALOGO_DB_USER:postgres}
    password: ${CATALOGO_DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
services:
  producto-url: ${PRODUCTO_URL:http://localhost:8082}
