spring:
  config:
    import: optional:file:.env[.properties]
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:}
          jwk-set-uri: ${JWT_JWK_SET_URI:}

server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    org.springframework.security: DEBUG

microservicios:
  perfil:
    url: ${MS_PERFIL_URL:http://localhost:8081}