server:
  port: ${PRODUCTO_PORT:8082}
spring:
  application:
    name: msvc-producto
  datasource:
    url: ${PRODUCTO_DB_URL:jdbc:postgresql://localhost:5434/producto_db}
    username: ${PRODUCTO_DB_USER:postgres}
    password: ${PRODUCTO_DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
