server:
  port: ${PAGO_PORT:8085}
spring:
  application:
    name: msvc-pago
  datasource:
    url: ${PAGO_DB_URL:jdbc:postgresql://localhost:5437/pago_db}
    username: ${PAGO_DB_USER:postgres}
    password: ${PAGO_DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
services:
  producto-url: ${PRODUCTO_URL:http://localhost:8082}
  carrito-url: ${CARRITO_URL:http://localhost:8083}
  envio-url: ${ENVIO_URL:http://localhost:8086}
